apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # Use NodePort or ClusterIP for other use cases
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80